### ISSUE TITLE
Error python manage.py migrate

### ISSUE THREAD

**Issue by galaxydata** [wildfish/wildfish-django-starter#10]
```
test:~/files/GitLab/new_geo/geometrika$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from configurations.management import execute_from_command_line
  File "/usr/local/lib/python2.7/dist-packages/configurations/management.py", line 3, in <module>
    importer.install(check_options=True)
  File "/usr/local/lib/python2.7/dist-packages/configurations/importer.py", line 49, in install
    importer = ConfigurationImporter(check_options=check_options)
  File "/usr/local/lib/python2.7/dist-packages/configurations/importer.py", line 67, in __init__
    self.check_options()
  File "/usr/local/lib/python2.7/dist-packages/configurations/importer.py", line 85, in check_options
    parser = base.CommandParser(None,
AttributeError: 'module' object has no attribute 'CommandParser'
```

**Comment by rolo** [comment]
Hi there.

Do you know which version of Django you're using? Could you please let me know the output of `python manage.py version`?

Also, it's looking for Django in your global system wide Python modules. Is this intentional? (happy to explain in more detail you want).

Thanks.

**Comment by rolo** [comment]
Am going to close this. @galaxydata please hollar if you're still having problems.
